# Generated by Django 4.1.1 on 2022-10-20 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0002_playlists_playlists_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
        migrations.RenameModel(
            old_name='Playlists_groups',
            new_name='Playlist_group',
        ),
    ]
