# Generated by Django 4.1.3 on 2022-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_music_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image_colors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
