# Generated by Django 4.1.3 on 2022-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_music_image_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image_colors',
            field=models.CharField(default='[(0,0,0)]', max_length=500),
        ),
    ]
