# Generated by Django 4.1.1 on 2022-10-22 07:26

from django.db import migrations, models
import musics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_music_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.FileField(upload_to='music_images/', validators=[musics.validators.validate_is_img]),
        ),
    ]
