# Generated by Django 4.1.3 on 2022-11-28 17:52

import django.core.files.storage
from django.db import migrations, models
import musics.validators
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_alter_music_image_colors_alter_music_time_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.FileField(default='settings.STATIC_ROOT/img/default-playlist-img.png', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/ionmo/Documents/gionify/media_root')), upload_to='music_images/', validators=[musics.validators.validate_is_img]),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_colors',
            field=models.CharField(default='["0,0,0","0,0,0","0,0,0"]', max_length=500),
        ),
    ]
