# Generated by Django 4.1.1 on 2022-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user_id',
        ),
    ]
