# Generated by Django 4.1.3 on 2022-11-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_alter_playlist_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='cover_image',
        ),
    ]
