# Generated by Django 4.1.1 on 2022-10-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_rename_username_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
