# Generated by Django 4.1.3 on 2022-12-08 04:19

import django.core.files.storage
from django.db import migrations, models
import musics.models
import musics.validators
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0015_playlist_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedplaylists',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='likedplaylists',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #71373', max_length=400),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.FileField(default=musics.models.random_img, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/ionmo/Documents/gionify/media_root')), upload_to='music_images/', validators=[musics.validators.validate_is_img]),
        ),
    ]
