# Generated by Django 4.1.3 on 2022-12-11 04:46

from django.db import migrations, models
import musics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0017_rename_user_id_playlist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #14177', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='profile_img/blank_profile.png', null=True, upload_to='music_images/', validators=[musics.validators.validate_is_img]),
        ),
    ]
