# Generated by Django 4.1.3 on 2022-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0019_artist_alter_userprofile_name_songartistgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Artist #76580', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #95416', max_length=400, null=True),
        ),
    ]
