# Generated by Django 4.1.3 on 2022-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0023_alter_artist_background_picture_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Artist #43189', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #90707', max_length=400, null=True),
        ),
    ]
