# Generated by Django 4.1.3 on 2022-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0026_alter_artist_name_alter_artist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Artist #62285', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #42555', max_length=400, null=True),
        ),
    ]
