# Generated by Django 4.1.3 on 2022-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0028_alter_artist_name_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='Artist #94550', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User #41204', max_length=400, null=True),
        ),
    ]
